### ISSUE TITLE
Can't deploy weblate in AKS

### ISSUE THREAD

**Issue by binte** [WeblateOrg/helm#61]
I tried to deploy weblate on AKS as per the following URL : https://docs.weblate.org/en/latest/admin/install/kubernetes.html

The weblate container keeps restarting. When I inspect the container logs, I can find the following entries: 

> STATEMENT: CREATE EXTENSION IF NOT EXISTS pg_trgm

> ERROR: permission denied to create extension "pg_trgm"

> Must be superuser to create this extension.

Any idea what I might be doing wrong?

**Comment by nijel** [comment]
See https://docs.weblate.org/en/latest/admin/install.html?highlight=pg_trgm#creating-a-database-in-postgresql

**Comment by maxsivkov** [comment]
> I tried to deploy weblate on AKS as per the following URL : https://docs.weblate.org/en/latest/admin/install/kubernetes.html
> 
> The weblate container keeps restarting. When I inspect the container logs, I can find the following entries:
> 
> > STATEMENT: CREATE EXTENSION IF NOT EXISTS pg_trgm
> 
> > ERROR: permission denied to create extension "pg_trgm"
> 
> > Must be superuser to create this extension.
> 
> Any idea what I might be doing wrong?

In this commit
https://github.com/WeblateOrg/helm/commit/0f73a39c03b625640d82e6caed6b113d63f9da10
default postgres user was changed from 'postgres' to 'weblate'
Because of this https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
Quoted:
>
>Note! The postgres user is a superuser and has full administrative access to the PostgreSQL database.
>
'weblate' user has no SUPERUSER rights anymore

**Resolution**
Set `postgresql.postgresqlUsername: "postgres"`  during helm install

**Comment by nijel** [comment]
That was introduced in https://github.com/WeblateOrg/helm/pull/60. Apparently not having PostgreSQL user set was there for a reason...
